apiVersion: apps/v1
kind: Deployment
metadata:
  name: geeko-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: geeko-frontend
  template:
    metadata:
      labels:
        app: geeko-frontend
    spec:
      containers:
        - name: geeko-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
