apiVersion: v1
kind: Service
metadata:
  name: geeko-frontend
spec:
  type: ClusterIP
  selector:
    app: geeko-frontend
  ports:
    - name: http
      appProtocol: http
      port: 80
      targetPort: 80
